name: Run tests for lesson 8
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  autotests-run:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '22.x'

       - name: Set up dependencies
         run: npm install --legacy-peer-deps

       - name: Run tests
         run: npm run test --tests/passwordStrength.test.ts








